interface IF_APC_WSP_EXTENSION_STATELESS
  public .


  interfaces IF_APC_WSP_EXTENSION .
  interfaces IF_APC_WSP_EXTENSION_COMMON .

  aliases CO_CONNECT_MODE_ACCEPT
    for IF_APC_WSP_EXTENSION~CO_CONNECT_MODE_ACCEPT .
  aliases CO_CONNECT_MODE_REJECT
    for IF_APC_WSP_EXTENSION~CO_CONNECT_MODE_REJECT .
  aliases ON_ACCEPT
    for IF_APC_WSP_EXTENSION~ON_ACCEPT .
  aliases ON_CLOSE
    for IF_APC_WSP_EXTENSION~ON_CLOSE .
  aliases ON_ERROR
    for IF_APC_WSP_EXTENSION~ON_ERROR .
  aliases ON_MESSAGE
    for IF_APC_WSP_EXTENSION~ON_MESSAGE .
  aliases ON_START
    for IF_APC_WSP_EXTENSION~ON_START .
endinterface.