*"* components of interface /IWBEP/IF_MGW_ODATA_PARAMETER
interface /IWBEP/IF_MGW_ODATA_PARAMETER
  public .


  interfaces /IWBEP/IF_MGW_ODATA_PROPERTY .

  aliases BIND_DATA_ELEMENT
    for /IWBEP/IF_MGW_ODATA_PROPERTY~BIND_DATA_ELEMENT .
  aliases CREATE_ANNOTATION
    for /IWBEP/IF_MGW_ODATA_ANNOTATABL~CREATE_ANNOTATION .
  aliases GET_ID
    for /IWBEP/IF_MGW_ODATA_ITEM~GET_ID .
  aliases SET_INTERNAL_TYPE
    for /IWBEP/IF_MGW_ODATA_PROPERTY~SET_INTERNAL_TYPE .
  aliases SET_LABEL_FROM_TEXT_ELEMENT
    for /IWBEP/IF_MGW_ODATA_ITEM~SET_LABEL_FROM_TEXT_ELEMENT .
  aliases SET_MAXLENGTH
    for /IWBEP/IF_MGW_ODATA_PROPERTY~SET_MAXLENGTH .
  aliases SET_NULLABLE
    for /IWBEP/IF_MGW_ODATA_PROPERTY~SET_NULLABLE .
  aliases SET_PRECISON
    for /IWBEP/IF_MGW_ODATA_PROPERTY~SET_PRECISON .
  aliases SET_SEMANTIC
    for /IWBEP/IF_MGW_ODATA_PROPERTY~SET_SEMANTIC .
  aliases SET_TEXT_KEY
    for /IWBEP/IF_MGW_ODATA_PROPERTY~SET_TEXT_KEY .
endinterface.