*"* components of interface /IWBEP/IF_MGW_ODATA_ACTION
interface /IWBEP/IF_MGW_ODATA_ACTION
  public .


  interfaces /IWBEP/IF_MGW_ODATA_ANNOTATABL .
  interfaces /IWBEP/IF_MGW_ODATA_ITEM .

  aliases GET_ID
    for /IWBEP/IF_MGW_ODATA_ITEM~GET_ID .
  aliases SET_LABEL_FROM_TEXT_ELEMENT
    for /IWBEP/IF_MGW_ODATA_ITEM~SET_LABEL_FROM_TEXT_ELEMENT .
  aliases SET_NAME
    for /IWBEP/IF_MGW_ODATA_ITEM~SET_NAME .

  types S type CHAR1 .

  methods GET_RETURN_ENTITY_TYPE
    returning
      value(RV_DATA_OBJECT_NAME) type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME .
  methods SET_RETURN_ENTITY_TYPE
    importing
      !IV_DATA_OBJECT_NAME type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME
    raising
      /IWBEP/CX_MGW_MED_EXCEPTION .
  methods GET_TECH_RETURN_ENTITY_TYPE
    returning
      value(RV_TECH_DATA_OBJECT_NAME) type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_INTERNAL_NAME .
  methods SET_RETURN_MULTIPLICITY
    importing
      !IV_CARDINALITY type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_CARDINALITY .
  methods GET_RETURN_MULTIPLICITY
    returning
      value(RV_CARDINALITY) type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_CARDINALITY .
  methods SET_HTTP_METHOD
    importing
      !IV_METHOD_NAME type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_HTTP_METHOD
    raising
      /IWBEP/CX_MGW_MED_EXCEPTION .
  methods CREATE_INPUT_PARAMETER
    importing
      !IV_PARAMETER_NAME type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME
      !IV_ABAP_FIELDNAME type FIELDNAME optional
    returning
      value(RO_PARAMETER) type ref to /IWBEP/IF_MGW_ODATA_PARAMETER
    raising
      /IWBEP/CX_MGW_MED_EXCEPTION .
  methods GET_RETURN_COMPLEX_TYPE
    returning
      value(RV_COMPLEX_TYPE_NAME) type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME .
  methods GET_INPUT_PARAMETERS
    returning
      value(RT_INPUT_PARAMETERS) type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_T_MED_PROPERTIES .
  methods SET_RETURN_COMPLEX_TYPE
    importing
      !IV_COMPLEX_TYPE_NAME type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME
    raising
      /IWBEP/CX_MGW_MED_EXCEPTION .
  methods SET_ACTION_FOR
    importing
      !IV_ENTITY_TYPE_NAME type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME
    raising
      /IWBEP/CX_MGW_MED_EXCEPTION .
  methods SET_DISABLED
    importing
      !IV_DISABLED type ABAP_BOOL default ABAP_TRUE .
  methods GET_INPUT_PARAMETER
    importing
      !IV_NAME type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME
    returning
      value(RO_INPUT_PARAMETER) type ref to /IWBEP/IF_MGW_ODATA_PROPERTY
    raising
      /IWBEP/CX_MGW_MED_EXCEPTION .
  methods SET_RETURN_ENTITY_SET
    importing
      !IV_ENTITY_SET_NAME type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME
    raising
      /IWBEP/CX_MGW_MED_EXCEPTION .
  methods BIND_INPUT_STRUCTURE
    importing
      !IV_STRUCTURE_NAME type STRING
      !IV_BIND_CONVERSIONS type ABAP_BOOL default ABAP_FALSE
    raising
      /IWBEP/CX_MGW_MED_EXCEPTION .
endinterface.