class CL_APC_TCP_EXT_STATELESS_BASE definition
  public
  abstract
  create public .

public section.

  interfaces IF_APC_WSP_EXTENSION_COMMON .
  interfaces IF_APC_TCP_SERVER_CONFIG
      abstract methods ON_CONNECTION_SETUP .
  interfaces IF_APC_WSP_EXTENSION
      abstract methods ON_MESSAGE
                       ON_START .
  interfaces IF_APC_WSP_EXTENSION_STATELESS .

  aliases CO_CONNECT_MODE_ACCEPT
    for IF_APC_WSP_EXTENSION_STATELESS~CO_CONNECT_MODE_ACCEPT .
  aliases CO_CONNECT_MODE_REJECT
    for IF_APC_WSP_EXTENSION_STATELESS~CO_CONNECT_MODE_REJECT .
  PROTECTED SECTION.
private section.

  aliases ON_ACCEPT
    for IF_APC_WSP_EXTENSION_STATELESS~ON_ACCEPT .
  aliases ON_CLOSE
    for IF_APC_WSP_EXTENSION_STATELESS~ON_CLOSE .
  aliases ON_CONNECTION_SETUP
    for IF_APC_TCP_SERVER_CONFIG~ON_CONNECTION_SETUP .
  aliases ON_ERROR
    for IF_APC_WSP_EXTENSION_STATELESS~ON_ERROR .
  aliases ON_MESSAGE
    for IF_APC_WSP_EXTENSION_STATELESS~ON_MESSAGE .
  aliases ON_START
    for IF_APC_WSP_EXTENSION_STATELESS~ON_START .
ENDCLASS.



CLASS CL_APC_TCP_EXT_STATELESS_BASE IMPLEMENTATION.


METHOD IF_APC_WSP_EXTENSION~ON_ACCEPT.
* ATTENTION ATTENTION ATTENTION ATTENTION
* DO NOT MODIFY THIS CODING BELONGING TO BASE CLASS
* APPLY THE CHANGES BY REDEFINING THE METHOD

* accept WebSocket connection setup
  e_connect_mode = co_connect_mode_accept.
ENDMETHOD.


METHOD IF_APC_WSP_EXTENSION~ON_CLOSE.
* ATTENTION ATTENTION ATTENTION ATTENTION
* DO NOT MODIFY THIS CODING BELONGING TO BASE CLASS
* APPLY THE CHANGES BY REDEFINING THE METHOD
*         (SEE NOTE 1816556 OR DOCUMENTATION)
* ATTENTION ATTENTION ATTENTION ATTENTION
ENDMETHOD.


METHOD IF_APC_WSP_EXTENSION~ON_ERROR.
* ATTENTION ATTENTION ATTENTION ATTENTION
* DO NOT MODIFY THIS CODING BELONGING TO BASE CLASS
* APPLY THE CHANGES BY REDEFINING THE METHOD
*         (SEE NOTE 1816556 OR DOCUMENTATION)
* ATTENTION ATTENTION ATTENTION ATTENTION
ENDMETHOD.
ENDCLASS.