interface IF_APC_WSP_INITIAL_REQUEST
  public .


  interfaces IF_APC_WS_INITIAL_REQUEST .

  aliases CO_FORMFIELD_ENCODING_ENCODED
    for IF_APC_WS_INITIAL_REQUEST~CO_FORMFIELD_ENCODING_ENCODED .
  aliases CO_FORMFIELD_ENCODING_RAW
    for IF_APC_WS_INITIAL_REQUEST~CO_FORMFIELD_ENCODING_RAW .
  aliases GET_COOKIE
    for IF_APC_WS_INITIAL_REQUEST~GET_COOKIE .
  aliases GET_COOKIES
    for IF_APC_WS_INITIAL_REQUEST~GET_COOKIES .
  aliases GET_FORM_FIELD
    for IF_APC_WS_INITIAL_REQUEST~GET_FORM_FIELD .
  aliases GET_FORM_FIELDS
    for IF_APC_WS_INITIAL_REQUEST~GET_FORM_FIELDS .
  aliases GET_FORM_FIELD_CS
    for IF_APC_WS_INITIAL_REQUEST~GET_FORM_FIELD_CS .
  aliases GET_HEADER_FIELD
    for IF_APC_WS_INITIAL_REQUEST~GET_HEADER_FIELD .
  aliases GET_HEADER_FIELDS
    for IF_APC_WS_INITIAL_REQUEST~GET_HEADER_FIELDS .
endinterface.